services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtt_network
    env_file:
      - .env
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/entrypoint.sh:/entrypoint.sh  
    entrypoint: /entrypoint.sh 

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mqtt_network
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env

  mqtt_service:
    build: 
      context: ./mqtt
      dockerfile: pymqtt.Dockerfile
    container_name: mqtt_service
    depends_on:
      - mosquitto
      - mongodb
    networks:
      - mqtt_network
    env_file: 
      - .env

networks:
  mqtt_network:
    driver: bridge

volumes:
  mongo_data:
